### ISSUE TITLE
Support for PiggyCustomEnchants?

### ISSUE THREAD

**Issue by ManiakMCPE** [JackNoordhuis/AutoInv#8]
When using a smelting pickaxe it doesn't give a smelted item.
I know this isn't really an **"issue"** but I would love to see it implemented.

**Comment by JackNoordhuis** [comment]
I don't know how 'PiggyCustomEnchants' works but if it sets the drops for the block break event correctly then AutoInv will behave as expected. 
https://github.com/JackNoordhuis/AutoInv-PocketMine/blob/c8192ec1f7f5dbdfdb40c30626ca65c3d2698483/src/jacknoordhuis/autoinv/event/handle/BlockBreakPickup.php#L44

**Comment by JackNoordhuis** [comment]
Changing the event priority here 
https://github.com/DaPigGuy/PiggyCustomEnchants/blob/abcc34e83d9c73da6eeb00102bb0aacc00890323/src/PiggyCustomEnchants/EventListener.php#L103 in PiggyCustomEnchants to 'HIGH' should fix your problem.

**Comment by ManiakMCPE** [comment]
Thank you :)
